name: Publish Extension
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: linux-x64
            npm_config_arch: x64
          - os: macOS-13
            target: darwin-x64
            npm_config_arch: x64
          - os: ubuntu-latest
            target: linux-arm64
            npm_config_arch: arm64
          - os: macos-latest
            target: darwin-arm64
            npm_config_arch: arm64
          - os: windows-latest
            target: win32-x64
            npm_config_arch: x64
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - name: Package Extension
        run: npx vsce package --target ${{ matrix.target }}
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: vsix-${{ matrix.target }}
          path: "*.vsix"
  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./vsix
      - name: Publish to Visual Studio Marketplace
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
        run: |
          if [ -z "${VSCE_PAT}" ]; then
            echo "VSCE_PAT secret not found. Skipping Visual Studio Marketplace publish."
          else
            for file in ./vsix/**/*.vsix; do
              echo "Publishing $file"
              npx vsce publish --pat "$VSCE_PAT" --packagePath "$file" || echo "Failed to publish $file to Marketplace"
            done
          fi
